### ISSUE TITLE
Building project with Vs2017/2019 does not work

### ISSUE THREAD

**Issue by Jiyuu** [AnkiTools/AnkiSharp#3]
When cloning this repository from github as is and attempting to load the csproj file and build it, the build fails.
The cause of this is that the nuget packages do not get restored, moreover the location of the resources from nuget is set to be at a level above the repository,
i.e. if you clone this repository into c:\Dev\AnkiSharp it will look for the Dlls in c:\Dev\packages

I would suggest either including the proper project structure, or adding a configuration for setting the package location inside the project.

**Comment by Jiyuu** [comment]
For anyone else that gets this, a workaround is Adding another project to the solution, and copying the packages.config content into it.
upon opening the "manage nuget packages" for the new project it gives the option to restore nuget which properly restores the packages.

**Comment by Jiyuu** [comment]
finally, it seems the cause of the build issue is having 

 ```
 <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0-*" PrivateAssets="All" />
    <PackageReference Include="Newtonsoft.Json">
      <Version>11.0.2</Version>
    </PackageReference>
    <PackageReference Include="sqlite-net-pcl">
      <Version>1.5.231</Version>
    </PackageReference>
  </ItemGroup>
```

this block in the csproj file, removing this block and reloading the project enables nuget restore, and the build completes successfully.

**Comment by Clement-Jean** [comment]
I'm trying to restart this from the ground up, @Jiyuu if you are interested in helping me, contact me on my email address

**Comment by Jiyuu** [comment]
i actually ended up re implementing parts of this on my own, but we can try cooperating on making something more public facing, sure

**Comment by Clement-Jean** [comment]
Ok nice, send me an email (you can find the address on my profile) and we’ll discuss about that

**Comment by Chobocharles** [comment]
I'm presuming that this issue is resolved?

**Comment by Clement-Jean** [comment]
This is not solved, I'm not working on this anymore but would be glad to accept PR
